# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#################################### BASIC SETTINGS ####################################
title: Medical Cheat Sheets
email: florianedem@gmail.com
tagline: "Un simple blog au sujet de diverses pathologies médicales"
description: >
  Un blog personnel ouvert à la contribution de tous les professionnels de la santé
  pour partager des fiches de synthèse sur diverses pathologies médicales.
keywords: >
  médecine, santé, pathologies, fiches, synthèse, médical, cheat sheets, mcs, médical,
  blog, maladies, maladie, pathologie, pathologies, médecin, infirmier, infirmière, aide-soignant,
  aide-soignante, étudiant, étudiante, santé, santé publique, santé communautaire, santé mentale, santé,
  endocrinologie, cardiologie, pneumologie, gastro-entérologie, hépatologie, néphrologie, rhumatologie,
  neurologie, dermatologie, infectiologie, hématologie, oncologie, gynécologie, obstétrique, pédiatrie,
  psychiatrie, chirurgie, orthopédie, traumatologie, urologie, ophtalmologie, oto-rhino-laryngologie,
  stomatologie, médecine interne, médecine générale, médecine d'urgence, médecine du travail
author: Florian Eudes C. EDEMESSI
locale: "fr_FR"
encoding: UTF-8
markdown: kramdown
highlighter: rouge
permalink: pretty
baseurl: "/mcs" # the subpath of your site, e.g. /blog
url: "https://nair0lf32.gihub.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: nair0lf32
logo: /assets/images/MCS.png
image: "https://raw.githubusercontent.com/nair0lf32/MedicalCheatSheets/master/assets/images/MCS.png"
twitter:
  username: florianedemessi
  card: summary
twitter_username: florianedemessi
social:
  name: EDEMESSI Florian
  links:
    - https://twitter.com/florianedemessi
    - https://www.facebook.com/nair0lf32
    - https://www.linkedin.com/in/florian-edemessi
    - https://github.com/nair0lf32
    - https://keybase.io/nair0lf32
# Collections
collections:
  authors:
    output: true
# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-pwa-workbox
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-glossary_tooltip
  - jekyll-spaceship
  - jekyll-language-plugin
  - jekyll-target-blank
  - jekyll-github-metadata
  - premonition
destination: ./_site
include:
  - static
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
theme: jekyll-theme-cayman


#################################### PWA SETTINGS ####################################

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  # precache_recent_posts_num: number # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/**/*.{ico,jpg,jpeg,png,svg}"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"

