name: jekyll-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: jekyll-deploy-gh-pages
      # You may pin to the exact commit or the version.
      # uses: BryanSchuetz/jekyll-deploy-gh-pages@c65ae23c7f03c25370004f16cba53110df1a4da4
      uses: BryanSchuetz/jekyll-deploy-gh-pages@v2.0
